
version: "3.1"

services:
  database:
    build: 
       context: database
    image: ddev_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB: ddev
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  api:
    build:
       context: api
    image: ddev_api
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  ui:
    build:
      context: ui
      # dockerfile: Dockerfile.debug
    image: ddev_ui
    ports:
      - "3000:3000"
      # - "5858:5858"
    networks:
      - front-tier

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
    
networks:
  front-tier:
  back-tier: